# Generated by Django 4.0.3 on 2022-03-29 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='file',
            managers=[
                ('list', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
