# Generated by Django 4.0.3 on 2022-05-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_alter_file_managers_file_file_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='file',
            managers=[
            ],
        ),
    ]
