# Generated by Django 4.0.3 on 2022-05-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='color',
            field=models.IntegerField(default=0),
        ),
    ]
